[directory]
truncate_to_repo = false
read_only = " "

[git_branch]
symbol = " "

[package]
format = "[$symbol$version]($style) "
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[[battery.display]]
threshold = 20
style = "bold red"

[java]
style = "red"